### ISSUE TITLE
Feather Sprite and CSS background-image

### ISSUE THREAD

**Issue by GreatPotato** [feathericons/feather#765]
Does anybody know of a way you can use the feather sprite with a css background image? I would have thought the below would have worked but it doesn't.

`.list-checkbox {
	list-style: none;
	
	li:before {
		content: "";
		display: inline-block;
		width: 1rem;
		height: 1rem;
		background-image: url('data:image/svg+xml;utf8,<svg class="feather"><use xlink:href="../img/feather.svg#check-square"/></svg>');
		stroke: currentColor;
		stroke-width: 1;
		stroke-linecap: round;
		stroke-linejoin: round;
		fill: none;
	}
}`

Any help appreciated!

**Comment by xphip** [comment]
I have very little CSS knowledge, but I hope it clarifies a bit.

```css
i[data-feather] {
	position: relative;
	display: inline-block;
	width: 24px;
	height: 24px;
}
i[data-feather]:after {
	position: absolute;
	content: " ";
	width: 24px;
	height: 24px;
	background: transparent center center no-repeat;
	background-size: 24px 24px;
}

i[data-feather="activity"]:after { background-image: url(../icons/activity.svg); }
...
```

**Comment by GreatPotato** [comment]
But this doesn’t use the feather sprite (which I want to use to reduce http requests)

**Comment by xphip** [comment]
Forgive me for my mistake.
For some reason `feather.svg` (inside `xlink:href`) is not firing when formatted as Data URI.

The best way I've found for now is to compress and create a stylesheet with all the SVG's embedded.
For example:
```css
i[data-feather="check-square"]:after {
	background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 11l3 3L22 4"/><path d="M21 12v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5a2 2 0 012-2h11"/></svg>');
}
```
It doubled the file size (feather.svg) but reduced the number of requests.
